sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t slaneslane/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true slaneslane/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "eu-west-1"
  app: "docker-react"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-eu-west-1-193510756091"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY

